doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                unix_socket: /Applications/MAMP/tmp/mysql/mysql.sock
            
            marprime:
                url: '%env(resolve:DATABASE_MARPRIME_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                unix_socket: /Applications/MAMP/tmp/mysql/mysql.sock

            marnoon:
                url: '%env(resolve:DATABASE_MARNOON_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                unix_socket: /Applications/MAMP/tmp/mysql/mysql.sock

            daily_transfer:
                url: '%env(resolve:DATABASE_DAILY_TRANSFER_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                unix_socket: /Applications/MAMP/tmp/mysql/mysql.sock

            pmi:
                url: '%env(resolve:DATABASE_PMI_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                unix_socket: /Applications/MAMP/tmp/mysql/mysql.sock



        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        default_entity_manager: default
 
        entity_managers:
            auto_generate_proxy_classes: true
#            naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
            auto_mapping: true
            default:
                connection: default
                mappings:

                    Default:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/UsrWeb71'
                        prefix: 'App\Entity\UsrWeb71'
                        alias: UsrWeb71
            marprime:
                connection: marprime
                mappings:
                        Marprime:
                            is_bundle: false
                            type: annotation
                            dir: '%kernel.project_dir%/src/Entity/Marprime'
                            prefix: 'App\Entity\Marprime'
                            alias: Marprime 
