# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    msc_interface:
        reports:
            upload_path: '%env(string:REPORT_PATH)%'
        mail:
            max_size: 4194304
        7z:
            bin: '%env(string:SEVENZ_BINARY)%' #/kunden/pages/1b/84/d0010915/home/bin/7za
        mpi:
            #Entschlüsselungsdaten
            secret_key: 'inspection123456'
            init_vector: 'kASD-vfäa3bP9§'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    logger:
        alias: 'monolog.logger'
        public: true

    maridis.mail.formatter:
        # alias: 'maridis.mail.formater'
        class: App\Maridis\Formatter\Mail
        

    # erstmal auskommentiert da es bei bin/console debug:autowiring sonst probleme gab
    #property_accessor:
    #    public: true

    lumturo.imap: 
        class: App\Service\Maridis\Imap
        arguments: ["%secit.imap.connections%"]
        public: true
